trigger:
- main

pool:
  name: Default

steps:
# Use the JFrog Artifactory NuGet restore task
- task: ArtifactoryNuGet@2
  inputs:
    command: 'restore'
    artifactoryService: 'rt'
    targetResolveRepo: 'jeremyl-nuget'
    solutionPath: 'MySolution.sln'
    nugetProtocolVersion: 'v3'

# Optional: Add other steps like build, test, deploy, etc.
- script: echo "Build and deploy steps would go here"
  displayName: 'Run build and deploy steps'

